### PR TITLE
UI/UX Enhancements: Color scheme, layout, and interactivity

### PR DESCRIPTION
**Pull request by amm10090**
- Updated color scheme for better visual hierarchy
- Improved layout and z-index for smoother UI
- Enhanced interactivity with transitions and hover effects
- Optimized responsive design for small screens
- Improved accessibility (reduced motion, high contrast)
- Added animations for better user feedback
- Refactored CSS for improved structure and readability

### CODE REVIEW

**Review by rdbhost — COMMENTED** [review]
Is this correct?

github-review-1

**Comment by amm10090** [comment]
This section can be deleted

```
/* Rounded corners for first and last header cells */
thead tr:first-child th:first-child {
	border-top-left-radius: 1rem;
}
thead tr:first-child th:last-child {
	border-top-right-radius: 1rem;
}
```

**Comment by rdbhost** [comment]
Then why are those lines included?

**Comment by rdbhost** [comment]
No, I'm not going to delete them, I am going to correct them.

**Comment by amm10090** [comment]
Mainly added to prevent being overridden by other styles

**Comment by rdbhost** [comment]
Yes, they were redundant, so I removed them.  

Looks good.

**Pull request merged**
