### PR TITLE
Three changes

### PR DESCRIPTION
**Pull request by amm10090**
Drag handle larger,
delete row button smaller
Disable hover style of th.min

### CODE REVIEW

**Comment by amm10090** [comment]
The problem of excessive column width when entering

**Comment by amm10090** [comment]
1. Set fixed width and height for the result cell
2. Adjust main.js and test.html files, add a delete all button to the title row,
3. Adjust the rounded corners
4. Background color of the incorrect cell
5. When the displayed content exceeds, the error message does not wrap and allows the background color to overflow.

**Comment by amm10090** [comment]
Style Adjustment:
Delete button on the same line as the title text
Error cell style adjustment
Default cell style adjustment
Correct cell style adjustment
Delete result button style update
Cell content centering
Cell Width Adaptive


Functional adjustments:
Each result column can be deleted individually
Fix add-alt function in main.js

**Review by rdbhost — CHANGES_REQUESTED** [review]
Please remove all of the JavaScript changes.
It seems that you overwrote all upstream changes when you merged.  Either way, I would rather do the JavaScript changes myself.

**Pull request merged**
